name: NuGet Generation

on:
  push:
    branches:
      - develop

jobs:
  build:
    runs-on: windows-latest
    name: Update NuGet 
    steps:

      - name: Checkout repository
        uses: actions/checkout@develop

      - name: Build solution and generate NuGet package
        run: |  
          cd SOLUTION_FOLDER
          dotnet pack -c Release -o out  
      - name: Install NuGet client
        uses: warrenbuckley/Setup-Nuget@v1

      - name: Add private GitHub registry to NuGet
        run: nuget sources add -name "GPR" -Source https://nuget.pkg.github.com/Task-Manager-Software/index.json -Username Task-Manager-Software -Password ${{ secrets.GITHUB_TOKEN }}

      - name: Push generated package to GitHub registry
        run: nuget push .\ModelDotnetCore\Model.DotNetCore\out\*.nupkg -Source "GPR" -SkipDuplicate
