name: .NET Core

on: [push]

jobs:
  publish-gpr:
    runs-on: windows-latest
    steps:
    - uses: einaregilsson/build-number@v1
      with:
        token: ${{secrets.GITHUB_TOKEN}}
    - uses: actions/checkout@v1
    - uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.100
    - uses: warrenbuckley/Setup-Nuget@v1
    - run: dotnet pack --configuration Release /p:Version=1.1.0.$env:BUILD_NUMBER --output $env:GITHUB_WORKSPACE
      env:
        DOTNET_SKIP_FIRST_TIME_EXPERIENCE: true
        DOTNET_CLI_TELEMETRY_OPTOUT: 1
    - run: nuget sources Add -Name "GPR" -Source https://nuget.pkg.github.com/Task-Manager-Software/index.json -UserName ${{github.actor}} -Password a3eee167e69d1267f932d5a553e2d38ede6b88cd
    - run: nuget push $env:GITHUB_WORKSPACE\*.nupkg -Source "GPR"
      env:
        GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
